### ISSUE TITLE
Add ability to generate layouttpl modules

### ISSUE THREAD

**Issue by natecavanaugh** [liferay/generator-liferay-theme#10]
@Robert-Frampton 
I got a request today asking about generating layouts (such as the ones from the SDK like 1-2-1-columns-layouttpl).

I can see two possible use cases:

1. Creating a standalone layout that can be deployed on it's own
2. Creating a layout that is bundled (and deployed) as part of the theme.

So maybe something along the lines of:
`yo liferay-theme:layout`

and from inside of a theme itself

`yo liferay-theme:theme-layout`?

What do you think?

**Comment by Robert-Frampton** [comment]
I think it would be pretty easy to implement, layouts aren't very complicated packages. Would we want to provide different layouts (1-2, 2-1, etc.) that they can modify, or just generate a really simple 1-column layout and let them do the rest?

**Comment by natecavanaugh** [comment]
I would imagine for now we could could just generate a really simple one, but I can imagine it would be really cool if we had some way to describe the layout rows/columns during the generation.
I had 2 possible thoughts on this:
1. Maybe some sort of DSL like the syntax in [Emmet](http://emmet.io/) where we could say: row>col*2+row>col+row>col*2 (which would generate a 2-1-2 layout), but that syntax might be a little hard to grasp
2. The other idea was some sort of layout builder in the terminal, perhaps with inquisitor where we prompt them with a series of questions (such as `How many rows?: 3, How many columns in the first row?...`). Or even something else like [Blessed](https://github.com/chjj/blessed) where we handle it visually (this might be overkill though).

Or if you have any ideas for how to present that, I'm open to hearing them :)

**Comment by Robert-Frampton** [comment]
I have a working example for the layout generator on my [dev branch](https://github.com/Robert-Frampton/generator-liferay-theme/tree/dev). Instead of having two different generators, this one just behaves differently depending on whether you run it in a theme or not, so it won't create the layouttpl meta data if you're inside a theme.

For generating the columns and rows, I like the idea of using inquirer, since it would be consistent with all of our other tools and it breaks down the process into easily digestible parts. We could also give them a preview of what it would look like once their done, and give them the option to start over if they messed something up.

**Comment by Robert-Frampton** [comment]
Available since v7.1.4.
