### ISSUE TITLE
How to control lexicon version installed in a new theme?

### ISSUE THREAD

**Issue by caneta** [liferay/generator-liferay-theme#15]
I've created a theme several months ago and the Lexicon version used at that time was 1.0.7:
```
user@host$ head -n 3 my-old-theme/build/css/aui/lexicon/lexicon-base.scss 
/**
* Lexicon 1.0.7
*
```
Now, I've created another theme and Lexicon seems to be updated to 1.0.13:

```
user@host$ head -n 3 my-new-theme/build/css/aui/lexicon/lexicon-base.scss 
/**
* Lexicon 1.0.13
*
```
I've find out that this is due to the application of the [latest patch](https://issues.liferay.com/browse/LPS-69470?jql=labels%20%3D%20liferay-fixpack-de-9-7010) for my Liferay DXP installation, but I have 2 questions anyway:

1. Is there a way to control Lexicon version during new theme creation?
2. Is there a way to update Lexicon (and other FE deps) for an old version of a theme, without recreating a new theme from scratch and copying inside all the work made for the old one?

Thank you

**Comment by Robert-Frampton** [comment]
Hey @caneta 

1. This one is a bit tricky as Lexicon comes bundled with [liferay-frontend-theme-unstyled]. If you look in the your theme's `package.json` you'll see `liferay-theme-deps-7.0`. This package is responsible for installing the base themes (liferay-frontend-theme-unstyled) and scss compiler.

One option you have is to remove `liferay-theme-deps-7.0` and declare those dependencies directly in the theme's `packge.json` which let's you explicitly set the version. Another idea is to add [lexicon-ux](https://www.npmjs.com/package/lexicon-ux) as a dependency and import that into your theme's `_aui.scss` file instead of the lexicon bundled with unstyled, but this method is going to be more prone to side effects.

2. If you just reinstall the `npm` dependencies of your theme it should pull down the latest versions.

Let me know if you need clarification for those two options. Hopefully we can simplify this in the future.

**Comment by caneta** [comment]
Ok, got it.
Thank you Robert!

**Comment by caneta** [comment]
`npm install` or `npm update` inside theme directory does not do the trick: if I build again my theme the lexicon version is still the old one...

**Comment by Robert-Frampton** [comment]
Did you try deleting `node_modules` and doing a fresh install?

**Comment by caneta** [comment]
Yes, deleting `node_modules` worked, thanks.
